#!/usr/local/bin/python 

# this python file iterates through the `.bash_profile`
# file to get all alias. it then prints out all the 
# available alias defined.

with open("/Users/liujingyu/.bash_profile", "r") as bash_profile:
  raw = bash_profile.readlines()

if __name__ == "__main__":
    print("\033[1;95mALIAS FROM $HOME/.bash_profile\033[0m")
    for line in raw:
        if line.startswith("alias"):
            useful = line[6:].strip()
            index = useful.find("=")
            if index != -1:
                alias = useful[:index]
                redirect = useful[index+1:]
                print("\033[1;93m"+alias+"\033[0m", end="\t")
                print("\033[1;92m"+redirect+"\033[0m")

