#!/usr/local/bin/python3


# This script changes the color schemes
# of LazyVim.
#
# List of all colorschemes available
# can be found in /usr/share/vim/vim90/colors.

from sys import argv
from os import system, listdir


if __name__ == "__main__":
    if len(argv) != 2:
        print("Wrong number of arguments! Expected 1 following `nvc`.")
        print()
        print(*listdir("/usr/share/vim/vim90/colors"), sep="\t\t")
        print()
        print(*listdir("/Users/liujingyu/.config/nvim/lua/plugins"), sep="\t\t")
        exit(0)
    color = argv[1]
    with open("/Users/liujingyu/.config/nvim/init.lua", "r") as lua:
        lines = lua.readlines()
    for i, l in enumerate(lines):
        if l.startswith("vim.cmd.colorscheme"):
            lines[i] = f'vim.cmd.colorscheme("{color}")\n'
    with open("/Users/liujingyu/.config/nvim/init.lua", "w") as lua:
        lua.writelines(lines)

    print("Color scheme changed to", color)
    system("nvim")
